version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  buildpack_deps:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle

jobs:
  build-job:
    executor: buildpack_deps
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
  publish-job:
    executor: buildpack_deps
    steps:
      #- slack/notify:
      #    message: Initiating Website Publishing
      - gh-pages/deploy:
          build-dir: _site
          ssh-fingerprints: '79:c4:dc:91:ff:31:4f:92:49:a3:91:39:5b:50:a8:a2'
      - slack/notify:
          message: Website Publishing Done

workflows:
  version: 2
  publish-deploy:
    jobs:
      - build-job
      - approval-publish-job:
          type: approval
          requires:
            - build-job
          filters:
            branches:
              only: master
      - publish-job:
          requires:
            - approval-publish-job
          filters:
            branches:
              only: master