name: Build and deploy jekyll site

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Slack Notification
        uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: alerts
          payload: >-
            {
              "icon_emoji": ":rocket:",
              "username": "Github Action",
              "attachments": [
                {
                  "author_name": "${{ github.event.sender.login }}",
                  "author_link": "${{ github.event.sender.html_url }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "color": "good",
                  "fallback": "Deployment finished.",
                  "pretext": "Deployment finished.",
                  "fields": [
                    {
                      "title": "Revision",
                      "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                      "short": true
                    }
                  ],
                  "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
              ]
            }